# Generated by Django 6.0.3 on 2026-03-27 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0003_alter_wallet_private_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=100, unique=True)),
                ('transaction_type', models.CharField(choices=[('WITHDRAWAL', 'Withdrawal'), ('SWAP', 'Swap'), ('DEPOSIT', 'Deposit')], max_length=20)),
                ('from_token', models.CharField(blank=True, max_length=100, null=True)),
                ('to_token', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
