# Generated by Django 6.0.3 on 2026-03-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_remove_wallet_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='private_key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
